### ISSUE TITLE
Drag cycle backward doesn't work

### ISSUE THREAD

**Issue by ShadyZOZ** [chinabrant/BBannerView#1]
Hello,
I found out the a small bug causing the backward drag won't work.

line 147, page should start from 1

``` swift
var page = Int(scrollView.contentOffset.x / scrollView.frame.size.width) + 1
```

but line 150, condition 

``` swift
} else if page == 0 {
```

should change to

``` swift
} else if page == 1 {
```

this should fix the problem

**Comment by chinabrant** [comment]
thank you, i will fix it
