### ISSUE TITLE
滑动问题

### ISSUE THREAD

**Issue by Agent-4** [chinabrant/BBannerView#3]
我发现一个问题：总共有3张图片，从第1张图片手动右滑—>，这本该是要滑到第3张图片的，但滑动瞬间就变成了第3张图片，完成那个右滑动作，反而滑到了第2张图片了。不知道你有没有发现这个问题，还是你是这样设计的？

**Comment by chinabrant** [comment]
是有个bug，我解决一下。

**Comment by chinabrant** [comment]
回归oc了，一直没搞，今天无事，解决了。
